services:
  node:
    container_name: client_react
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "80:80"
            
